bases:
  - ../helm-defaults.yaml
  - ../environments.yaml
---

repositories:
  - name: hashicorp
    url: https://helm.releases.hashicorp.com
  - name: incubator
    url: https://kubernetes-charts-incubator.storage.googleapis.com

helmDefaults:
  createNamespace: true

releases:
  - name: vault
    namespace: vault
    labels:
      chart: "hashicorp/vault"
      repo: "hashicorp"
      component: "vault"
      namespace: "vault"
      vendor: "hashicorp"
    chart: incubator/raw
    version: {{ .Values.raw.chart_version | quote }}
    dependencies:
      - alias: vault
        chart: hashicorp/vault
        version: {{ .Values.vault.chart_version | quote }}
    wait: true
    timeout: 90
    atomic: true
    cleanupOnFail: true
    installed: {{ .Values.installed }}
    values:
      - init.yaml.gotmpl
      - vault.yaml.gotmpl
  # This release deploys an Istio-based ingress gateway that includes public DNS & a public certificate
  - name: vault-gateway
    namespace: vault
    chart: incubator/raw
    version: {{ .Values.raw.chart_version | quote }}
    wait: true
    timeout: 180
    atomic: true
    cleanupOnFail: true
    installed: {{ .Values.installed }}
    values:
      - vault-gateway.yaml.gotmpl
